services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - backend/.env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "80:80"
